---
title: "Class16"
author: "Maris Sala"
date: "5/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(pacman, tidyverse, R2jags, modules)
set.seed(1985)
#qc <- modules::import("../jags_helpfuns/quick_n_clean_plots", attach = T, doc = T)
#modules::reload(qc)
#source("CC.R")
#source("EWA.R")
```

```{r}
source("R_fun/EWA.R")
source("R_fun/CC.R")
n_agents <- 3
n_trials <- 15
n_tokens <- 20
pi <- 1.2 #number that we multiply the common goods pool with
dat_ewa <- EWA(n_agents, n_trials, n_tokens, pi, 
           delta=runif(n_agents, 0.2, 0.4),
           rho=runif(n_agents, 0.5, 0.9),
           phi=runif(n_agents, 0.4, 0.8),
           lambda=runif(n_agents, 0.8, 2))

c <- dat_ewa$choice
group_c <- array(0,c(n_agents,n_trials))
for (n in 1:n_agents) {
  group_c[n,] <- colSums(c[-n,])
}
group_c
dat_ewa$choice
dat_ewa$internal_states$phi #retention of attractions, memory decay, downwighting prior attractions, the bigger the phi, the more you downweigh prior attractions, the higher phi the more previous stuff matters (most consistent!)

# CC
parameters = list(
  gb_1 = round(runif(n_agents, 1, 20), 0),
  omega_1 = runif(n_agents, 0, 1),
  lambda = runif(n_agents, 0, 0.5),
  gamma = runif(n_agents, 0, 1),
  p_0 = runif(n_agents, 0, 8),
  p_beta = runif(n_agents, 0, 1)
)
dat_cc <- CC(n_agents, n_trials, vals=seq(1, 20, 1), parameters)
dat_cc$c
dat_cc$parameters$p_0
dat_cc$parameters$p_beta
```

```{r jags}
# EWA
fit_ewa <- jags.parallel(data = list(n_agents=n_agents, 
                                 n_trials=n_trials, 
                                 n_tokens=n_tokens,
                                 c=dat_ewa$choice,
                                 #c_actual=dat_ewa$choice,
                                 group_c=group_c,
                                 pi=pi),
                     inits = NULL,
                     parameters.to.save = c("delta", "rho", "phi", "lambda"),
                     n.chains = 4, n.iter = 3000, n.burnin = 1000,
                     model.file = "jags_models/EWA_j.txt"
                     )
fit_ewa
## CC
fit <- jags.parallel(data = list(n_agents=n_agents, 
                                 n_trials=n_trials, 
                                 ga=dat_cc$ga,
                                 c=dat_cc$c,
                                 vals=dat_cc$vals),
                     inits = NULL,
                     parameters.to.save = c("omega_1", "lambda", "gamma", "p_0", "p_beta", "omega", "c"),
                     n.chains = 4, n.iter = 3000, n.burnin = 1000,
                     model.file = "jags_models/CC.txt"
                     )
fit
```