---
title: "Class11"
author: "Maris Sala"
date: "3/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is the PVL assignment done independently under corona lockdown

THE VSE MODEL

```{r}
set.seed(1982)
#setwd("~/Aarhus University/Advanced cog mod/progre")
pacman::p_load(extraDistr, R2jags)
```

Task environment - IGT but losses and gains need to be separate (no payoff matrix)

```{r}
RA <- A
RA[A < 0] = 100
RB <- B
RB[B < 0] = 100
RC <- C
RC[C <= 0] = 50
RD <- D
RD[D < 0] = 50

# extract losses from reward trials
LA <- A
LA[A > 0] = 0
LA[LA < 0] = -250
LB <- B
LB[B > 0] = 0
LB[LB < 0] = -1250
LC <- C
LC[C == 0] = -50
LC[LC > 1] = 0
LD <- D
LD[D > 0] = 0
LD[LD < 0] = -250

R <- cbind(RA,RB,RC,RD)
L <- cbind(LA,LB,LC,LD)
L <- abs(L)
R <- R

```

Build the VSE model
```{r}
# Risk preference for utility (0-1)
r_pref <- 0.2
# Decay rate for value learning function (0-1)
delta_rate <- .9
# a learning rate for the sequential exploration function (0-1)
a_explore <- .2
# a maximum/asymptote for the sequential exploration function (no bound)
phi <- 2
# Softmax inverse heat
theta <- 0.5

ntrials <- 100

source("R_fun/VSE.R")
VSE_sims <- VSE(L,R, ntrials, r_pref, delta_rate, a_explore, phi, theta)

par(mfrow=c(2,2))
plot(VSE_sims$explore[,1])
plot(VSE_sims$explore[,2])
plot(VSE_sims$explore[,3])
plot(VSE_sims$explore[,4])

par(mfrow=c(2,2))
plot(VSE_sims$exploit[,1])
plot(VSE_sims$exploit[,2])
plot(VSE_sims$exploit[,3])
plot(VSE_sims$exploit[,4])

#plot(VSE_sims$r)
plot(VSE_sims$x)
plot(VSE_sims$r)
plot(VSE_sims$l)
```

Run the jags model
```{r}
x <- VSE_sims$x
r <- VSE_sims$r
l <- VSE_sims$l

# Risk preference for utility (0-1)
r_pref <- 0.2
# Decay rate for value learning function (0-1)
delta_rate <- .9
# a learning rate for the sequential exploration function (0-1)
a_explore <- .2
# a maximum/asymptote for the sequential exploration function (no bound)
phi <- 2
# Softmax inverse heat
theta <- 0.5

ntrials <- 100

data <- list("x", "r", "l", "ntrials")
params <- c("r_pref", "delta_rate", "a_explore", "phi", "theta")

samples <- jags.parallel(data, inits = NULL, params,
                model.file = "jags_models/VSE.txt",
                n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1)

r_pref_infer <- samples$BUGSoutput$sims.list$r_pref
delta_rate_infer <- samples$BUGSoutput$sims.list$delta_rate
a_explore_infer <- samples$BUGSoutput$sims.list$a_explore
phi_infer <- samples$BUGSoutput$sims.list$phi
theta_infer <- samples$BUGSoutput$sims.list$theta

par(mfrow=c(2,3))
d <- density(r_pref_infer)
plot(d, main="VSE model: r_pref")
polygon(d, col="lightblue", border="lightblue")
d <- density(delta_rate_infer)
plot(d, main="VSE model: delta_rate")
polygon(d, col="lightblue", border="lightblue")
d <- density(a_explore_infer)
plot(d, main="VSE model: a_explore")
polygon(d, col="lightblue", border="lightblue")
d <- density(phi_infer)
plot(d, main="VSE model: phi")
polygon(d, col="lightblue", border="lightblue")
d <- density(theta_infer)
plot(d, main="VSE model: theta")
polygon(d, col="lightblue", border="lightblue")

median(r_pref_infer)
median(delta_rate_infer)
median(a_explore_infer)
median(phi_infer)
median(theta_infer)

```

Parameter recovery
```{r}
niterations <- 100
VSE_t.rp <- array(0, c(niterations))
VSE_t.dr <- array(0, c(niterations))
VSE_t.a <- array(0, c(niterations))
VSE_t.phi <- array(0, c(niterations))
VSE_t.theta <- array(0, c(niterations))

VSE_i.rp <- array(0, c(niterations))
VSE_i.dr <- array(0, c(niterations))
VSE_i.a <- array(0, c(niterations))
VSE_i.phi <- array(0, c(niterations))
VSE_i.theta <- array(0, c(niterations))

##
ntrials <- 100

for (i in 1:niterations) {
  # true parameters
  r_pref <- runif(1,0,1)
  delta_rate <- runif(1,0,1)
  a_explore <- runif(1,0,1)
  phi <- rnorm(1,0,5) # this shouldnt have bounds whats up
  theta <- runif(1,0,1)
  
  #run function and extract responses
  source("R_fun/VSE.R")
  VSE_sims <- VSE(L,R, ntrials, r_pref, delta_rate, a_explore, phi, theta)
  x <- VSE_sims$x
  r <- VSE_sims$r
  l <- VSE_sims$l
  
  data <- list("x", "r", "l", "ntrials")
  params <- c("r_pref", "delta_rate", "a_explore", "phi", "theta")

  samples <- jags.parallel(data, inits = NULL, params,
                  model.file = "jags_models/VSE.txt",
                  n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1)
  
  VSE_t.rp[i] <- r_pref
  VSE_t.dr[i] <- delta_rate
  VSE_t.a[i] <- a_explore
  VSE_t.phi[i] <- phi
  VSE_t.theta[i] <- theta
  
  #find max posteriori
  X <- samples$BUGSoutput$sims.list$r_pref
  VSE_i.rp[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$delta_rate
  VSE_i.dr[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$a_explore
  VSE_i.a[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$phi
  VSE_i.phi[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$theta
  VSE_i.theta[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  print(i); beepr::beep(sound=1)
}

beepr::beep(sound=3)

library(ggplot2)
#Beautiful plots
image_VSE_rp = plot_actual_predicted(VSE_t.rp, VSE_i.rp, caption = F)+
  ggtitle("VSE model: risk_pref") +
  theme_bw() +
  xlim(0,1) + ylim(0,1)
image_VSE_dr = plot_actual_predicted(VSE_t.dr, VSE_i.dr, caption = F)+
  ggtitle("VSE model: delta_rate") +
  theme_bw() +
  xlim(0,1) + ylim(0,1)
image_VSE_a = plot_actual_predicted(VSE_t.a, VSE_i.a, caption = F)+
  ggtitle("VSE model: a_explore") +
  theme_bw() +
  xlim(0,1) + ylim(0,1)
image_VSE_phi = plot_actual_predicted(VSE_t.phi, VSE_i.phi, caption = F)+
  ggtitle("VSE model: phi") +
  theme_bw() +
  xlim(-15,15) + ylim(-15,15)
image_VSE_theta = plot_actual_predicted(VSE_t.theta, VSE_i.theta, caption = F)+
  ggtitle("VSE model: theta") +
  theme_bw() +
  xlim(0,1) + ylim(0,1)

img_PVL_model <-  gridExtra::grid.arrange(image_VSE_rp, image_VSE_dr, ncol = 2)
gridExtra::grid.arrange(image_VSE_a, image_VSE_phi, image_VSE_theta, ncol=2)

# Save results
save.image("VSE_parameter_recovery.RData")

```


Comparing posteriors of true and inferred values

```{r}
par(mfrow=c(2,1))
d1 <- density(VSE_t.rp)
plot(d1, main="VSE model: risk_pref")
polygon(d1, col="lightblue", border="lightblue")
d2 <- density(VSE_i.rp)
plot(d2, main="VSE model: risk_pref")
polygon(d2, col="lightblue", border="lightblue")

par(mfrow=c(2,1))
d1 <- density(VSE_t.dr)
plot(d1, main="VSE model: delta_rate")
polygon(d1, col="lightblue", border="lightblue")
d2 <- density(VSE_i.dr)
plot(d2, main="VSE model: delta_rate")
polygon(d2, col="lightblue", border="lightblue")

par(mfrow=c(2,1))
d1 <- density(VSE_t.a)
plot(d1, main="VSE model: a_explore")
polygon(d1, col="lightblue", border="lightblue")
d2 <- density(VSE_i.a)
plot(d2, main="VSE model: a_explore")
polygon(d2, col="lightblue", border="lightblue")

par(mfrow=c(2,1))
d1 <- density(VSE_t.phi)
plot(d1, main="VSE model: phi")
polygon(d1, col="lightblue", border="lightblue")
d2 <- density(VSE_i.phi)
plot(d2, main="VSE model: phi")
polygon(d2, col="lightblue", border="lightblue")

par(mfrow=c(2,1))
d1 <- density(VSE_t.theta)
plot(d1, main="VSE model: theta")
polygon(d1, col="lightblue", border="lightblue")
d2 <- density(VSE_i.theta)
plot(d2, main="VSE model: theta")
polygon(d2, col="lightblue", border="lightblue")

```

