---
title: "Class6"
author: "Maris Sala"
date: "3/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(1982)
pacman::p_load(R2jags, extraDistr)
#setwd("~/Aarhus University/Advanced cog mod/progre")
```

Generate task environment
```{r}
ntrials <- 100

Aprob <- .3
Arew <- 2

Bprob <- .8
Brew <- 1

#generate a payoff matrix
payoff <- cbind(rbinom(ntrials, 1, Aprob) * Arew, rbinom(ntrials, 1, Bprob) * Brew) #why rbinom?

colSums(payoff)
```

Run the Rescola-Wagner model
```{r}
# lets call the function we wrote
# first give it some parameters

a <- .2
beta <- 1

source("R_fun/RW.R")

RW_sims <- RW(payoff, ntrials, a, beta)

par(mfrow=c(3,1)) #plot with 3 rows and 1 column
plot(RW_sims$Q[,1])
plot(RW_sims$Q[,2])
#plot(X)

```

recovering parameters with JAGS
```{r, include=FALSE}
X <- RW_sims$x
r <- RW_sims$r

data <- list("X", "r", "ntrials")
params <- c("a", "beta")

samples <- jags.parallel(data, inits = NULL, params,
                model.file = "jags_models/RW.txt",
                n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1)

a_infer <- samples$BUGSoutput$sims.list$a
beta_infer <- samples$BUGSoutput$sims.list$beta

par(mfrow=c(1,1))
plot(density(a_infer))
plot(density(beta_infer))

d <- density(a_infer)
plot(d, main="RW model: a")
polygon(d, col="lightblue", border="lightblue")
median(a_infer)

d <- density(beta_infer)
plot(d, main="RW model: beta")
polygon(d, col="lightblue", border="lightblue")
median(beta_infer)


#run full parameter recovery
niterations <- 100
true_a <- array(0, c(niterations))
true_beta <- array(0, c(niterations))

infer_a <- array(0,c(niterations))
infer_beta <- array(0,c(niterations))

for (i in 1:niterations) {
  # true parameters
  a <- runif(1,0,1)
  beta <- runif(1,0,5)
  
  #fun function and extract responses
  RW_sims <- RW(payoff, ntrials, a, beta)
  X <- RW_sims$x
  r <- RW_sims$r
  
  data <- list("X", "r", "ntrials")
  params <- c("a", "beta")

  samples <- jags.parallel(data, inits = NULL, params,
                  model.file = "jags_models/RW.txt",
                  n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1)
  true_a[i] <- a
  true_beta[i] <- beta
  
  #find max posteriori
  X <- samples$BUGSoutput$sims.list$a
  infer_a[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$beta
  infer_beta[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  print(i); beepr::beep(sound=1)
}

a_infer <- samples$BUGSoutput$sims.list$a
beta_infer <- samples$BUGSoutput$sims.list$beta

par(mfrow=c(1,1))
plot(density(a_infer))
plot(density(beta_infer))

#get plotting functions
source("quick_n_clean_plots.R")
infer_a
#Beautiful plots
image_a = plot_actual_predicted(true_a, infer_a, caption = F)+
  ggtitle("RW model: a") +
  theme_bw() +
  xlim(0,1) + ylim(0,1)
image_beta = plot_actual_predicted(true_beta, infer_beta, caption = F)+
  ggtitle("RW model: beta") +
  theme_bw() +
  xlim(0,5) + ylim(0,5)

img_rw_model <-  gridExtra::grid.arrange(image_a, image_beta, nrow=1)

#plot(density(inferredTheta))

```

