---
title: "Class9"
author: "Maris Sala"
date: "3/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(1982)
#setwd("~/Aarhus University/Advanced cog mod/progre")
pacman::p_load(extraDistr, R2jags)
```

Task environment - IGT so 4 decks instead of 2, plus both wins and losses (so we dont just copy previous task environment code)

```{r}
# Bad frequent
A_R <- rep(100,10) #reward for deck A, 10 outcomes
A_L <- c(rep(-250,5), rep(0,5)) #losses 50% of the times
# Bad infrequent
B_R <- rep(100,10)
B_L <- c(rep(-1250,1), rep(0,9)) #one big loss but very infrequent
# Good frequent
C_R <- rep(50,10)
C_L <- c(rep(-50,5), rep(0,5))
# Good infrequent
D_R <- rep(50,10)
D_L <- c(rep(-250,1), rep(0,9))

# For the forward simulations: shuffle the deck
# Set up the environment with separate wins and losses as if they will be presented separately to the participants
A <- c()
for (i in 1:10) { A <- (append(A,A_R + sample(A_L))) } # To each of the 4 decks, adds losses and rewards together

B <- c()
for (i in 1:10) { B <- (append(B,B_R + sample(B_L))) }

C <- c()
for (i in 1:10) { C <- (append(C,C_R + sample(C_L))) }

D <- c()
for (i in 1:10) { D <- (append(D,D_R + sample(D_L))) }

# The sums of taking only from one deck: -2500 or +2500
sum(A)
sum(B)
sum(C)
sum(D)

# Payoff matrix
payoff <- cbind(A,B,C,D)
```

Build the PVL-delta model
```{r}
w <- .1 # Loss aversion (2 from Khaneman)
A <- .5 # Shape of the utility function, between 0 and 1 to have the proper shape
theta <- 2 # Response consistency
a <- .01 # Learning rate

ntrials <- 100

source("R_fun/PVL.R")
PVL_sims <- PVL(payoff, ntrials, w, A, a, theta)

par(mfrow=c(2,2))
plot(PVL_sims$Ev[,1])
plot(PVL_sims$Ev[,2])
plot(PVL_sims$Ev[,3])
plot(PVL_sims$Ev[,4])
```

There is some error in the code! - plots one as flattened out on 0

```{r}
x <- PVL_sims$x
X <- PVL_sims$X

data <- list("x", "X", "ntrials")
params <- c("w", "A", "theta", "a")

samples <- jags.parallel(data, inits = NULL, params,
                model.file = "jags_models/PVL.txt",
                n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1)

a_infer <- samples$BUGSoutput$sims.list$a
w_infer <- samples$BUGSoutput$sims.list$w
A_infer <- samples$BUGSoutput$sims.list$A
theta_infer <- samples$BUGSoutput$sims.list$theta

#original numbers
w <- .1 # Loss aversion (2 from Khaneman)
A <- .5 # Shape of the utility function, between 0 and 1 to have the proper shape
theta <- 2 # Response consistency
a <- .01 # Learning rate

par(mfrow=c(1,1))
plot(density(a_infer))
plot(density(w_infer))
plot(density(A_infer))
plot(density(theta_infer))
```

Run parameter recovery
```{r}
plot(density(a_infer))
plot(density(w_infer))
plot(density(A_infer))
plot(density(theta_infer))

niterations <- 10
PVL_t.a <- array(0, c(niterations))
PVL_t.w <- array(0, c(niterations))
PVL_t.A <- array(0, c(niterations))
PVL_t.theta <- array(0, c(niterations))

PVL_i.a <- array(0, c(niterations))
PVL_i.w <- array(0, c(niterations))
PVL_i.A <- array(0, c(niterations))
PVL_i.theta <- array(0, c(niterations))

##
ntrials <- 100

for (i in 1:niterations) {
  # true parameters
  #a <- trunc(runif(1,0,1))
  a <- runif(1,0,1)
  #w <- rnorm(1,0,5)
  w <- trunc(rnorm(1,0,5))
  A <- runif(1,0,1)
  #A <- trunc(runif(1,0,1))
  theta <- trunc(rnorm(1,0,5))
  
  #fun function and extract responses
  source("R_fun/PVL.R")
  PVL_sims <- PVL(payoff, ntrials, w, A, a, theta)
  x <- PVL_sims$x
  X <- PVL_sims$X
  
  data <- list("X", "x", "ntrials")
  params <- c("w", "A", "theta", "a")

  samples <- jags.parallel(data, inits = NULL, params,
                  model.file = "jags_models/PVL.txt",
                  n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1)
  
  PVL_t.a[i] <- a
  PVL_t.w[i] <- w
  PVL_t.A[i] <- A
  PVL_t.theta[i] <- theta
  
  #find max posteriori
  X <- samples$BUGSoutput$sims.list$a
  PVL_i.a[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$w
  PVL_i.w[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$A
  PVL_i.A[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  X <- samples$BUGSoutput$sims.list$theta
  PVL_i.theta[i] <- density(X)$x[which(density(X)$y==max(density(X)$y))]
  
  print(i)
}

plot(PVL_t.a, PVL_i.a)
plot(PVL_t.w, PVL_i.w)
plot(PVL_t.A, PVL_i.A)
plot(PVL_t.theta, PVL_i.theta)
```

```{r}
# Generate data
 n <- 20
 p <- 2
 X <- rnorm(n)
 Y <- rnorm(n,X,1)

# Hyperpriors

 prec_beta <- 0.01
 a         <- 0.01
 b         <- 0.01

model_string <- "model{

  # Likelihood
  for(i in 1:n){
    Y[i] ~ dnorm(beta[1] + X[i]*beta[2],tau)
  }

  # Prior
  for(j in 1:p){beta[j] ~ dnorm(0, prec_beta)}
  tau ~ dgamma(a,b)

 }"

 library(rjags)
 X_miss    <- X  # Add a missing X
 X_miss[1] <- NA

 data  <- list(Y=Y,X=X_miss,p=p,n=n,prec_beta=prec_beta,a=a,b=b)
 keep  <- c("beta","tau")

 model <- jags.model(textConnection(model_string), data = data,quiet=TRUE)
```

